- name: calling varibles
  host: localhost #managing 
  var_files:
  - H:\devopstools\repos\ansible\variables.yaml
  tasks:
- name: variable printing
  ansible.builtin.debug:
     msg: "hello im learing {{course}}, attandee is {{attendee}} and duration is {{duration}}"
  



  