- name: varaible in yaml script
  hosts: mongodb
  vars:
    course: Devops
    NAME: saikumar-var
  
  tasks:
    - name: variables
      ansible.builtin.debug: # to run the inputs
        msg: "hello world"

    - name: print variable
      ansible.builtin.debug:
        msg: "hello im learing {{course}}, attandee is {{attendee}}"




