- name: check varaible level which preferring first
  hosts: mongodb
  vars: 
    NAME: saikumar
  vars-files:
    variables.yaml
  vars-prompt:
  - name: NAME
    Prompt: pls enter name
    private: false
  tasks: 
  - name: variable task level
    ansible.builtin.debug:
      msg: "trainer name: {{NAME}}"