- name: variables at task level
  hosts: localhost
  vars:
  - money: "100cr" 
    land: "10acres"
  tasks:
  - name:  at task level
    vars:
    - money: "200cr"
      land: "20acrs"
    ansible.builtin.debug:
      msg: "{{money}},{{land}},{{houses}} "
  