- name: variables at task level
  hosts: localhost
  vars:
  - money: 100cr
    land: 10acres
  tasks:
  - name:  at task level
    money: 200cr
    houses: 10
    ansible.builtin.debug:
      msg: "{{money}},{{land}},{{houses}} "
  